monorepo_root = true

[monorepo]
config_roots = []

[tools]
"aqua:mvdan/sh" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:actionlint" = "latest"
"aqua:zizmor" = "latest"
"aqua:ghalint" = "latest"
"aqua:suzuki-shunsuke/pinact" = "latest"

[env]
AWS_REGION = "ap-northeast-1"
PACKER_NETWORK_STACK_NAME = "isuren-mondai-packer-network"
