server {
  listen 443 ssl;
  server_name u.isuren.internal;
  server_name *.u.isuren.internal;

  ssl_certificate /etc/nginx/tls/pipe.u.isuren.internal.crt;
  ssl_certificate_key /etc/nginx/tls/pipe.u.isuren.internal.key;
  ssl_protocols TLSv1.3;
  ssl_prefer_server_ciphers off;

  client_max_body_size 10m;
  root /home/isuren/webapp/public;

  location / {
    try_files $uri /index.html;
  }

  location /api {
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:8080;
  }
}
